### ISSUE TITLE
NewsPapperPhotos

### ISSUE THREAD

**Issue by Hurfy** [Greavesy1899/Mafia2Toolkit#1]
![mpiuapzj6xq](https://user-images.githubusercontent.com/36721814/42377519-475cad9e-812c-11e8-85fe-d2293acd3664.jpg)
![7fyihy5907w](https://user-images.githubusercontent.com/36721814/42377520-47826afc-812c-11e8-87a5-74535bf9ac57.jpg)

**Comment by Greavesy1899** [comment]
What are these for?
