### ISSUE TITLE
Unidentified hash characters

### ISSUE THREAD

**Issue by afterdelight** [Greavesy1899/Mafia2Toolkit#21]
**Is your feature request related to a problem? 
I tried to edit human_dmgzones.tbl but it has unidentified hash from tables rows on .tbl file.

**Describe the solution you'd like**
Convert the unidentified hash to readable string.

**Comment by afterdelight** [comment]
Here is the screenshot.

![unidentified hash](https://user-images.githubusercontent.com/39585663/60850829-2b8d2d80-a21b-11e9-803b-cfac1a13ee3a.png)

**Comment by Greavesy1899** [comment]
The first row is actually the name of the column, but Mafia II's "tables" format doesn't store the name of each column, just the hash. 

I will make an improvement which swaps the hashes to the names of the columns, once I've figured them out.

**Comment by afterdelight** [comment]
![compare](https://user-images.githubusercontent.com/39585663/60928922-58077f00-a2d9-11e9-8508-314f233ecb0e.png)
So, I compare your tool with some russian coder and the original gib tool, notice the last row is 7E 33 63 2F and the russian program is 2F 63 33 7E. The characters was in a couple and the order is reversed between your tool and the russian program.

**Comment by afterdelight** [comment]
Found the hash type, it is FNV-1 (32-bit) :)

**Comment by Greavesy1899** [comment]
Yep, I'll implement some soon, if you want to figure out more column names, you can find a hash calculator online, enter the possible column name and hope the hash is the same as in the table editor.

**Comment by Greavesy1899** [comment]
Quick example:
![image](https://user-images.githubusercontent.com/26023883/60987605-ddbb1700-a339-11e9-8231-59917646356d.png)

**Comment by afterdelight** [comment]
I can't seem to find fnv132 decryptor/decoder. Can you point me to some?
Are the rest of the rows a different hash type?

**Comment by Greavesy1899** [comment]
This one is decent, enter the string below "Hash String" and look below for "fnv132"

https://www.pelock.com/products/hash-calculator

**Comment by Greavesy1899** [comment]
Download the latest version, and this should include table editor hashes.

**Comment by afterdelight** [comment]
Yes I already downloaded the new version days ago but the hashes.txt is not complete. I can't seem to find the type of other encoded hashes. I want to edit weapon.tbl. Do you know what type of hash it is?

**Comment by Greavesy1899** [comment]
The rest of the hashes are unknown, they still need to be figured out. I only released the latest version yesterday so I highly recommend redownloading.

**Comment by afterdelight** [comment]
Okay, downloaded.
