### ISSUE TITLE
Attempting to repack a sds with a file removed results in an error

### ISSUE THREAD

**Issue by 3371-Alpha** [Greavesy1899/Mafia2Toolkit#26]
If you remove a file from an unpacked sds and attempt to repack it it gives an unhandled exception error. This is inconvenient as I'm attempting to use a car replacement mod with the original car name by deleting tables/TextDatabase.dat and PREFAB_17.prf but the tool is preventing me.

**Comment by szymonuwu** [comment]
> If you remove a file from an unpacked sds and attempt to repack it it gives an unhandled exception error. 

Did you just removed a file? Mafia 2 sds archives have sdscontent.xml file inside with a list of files containing in sds archive.
Check sdscontent.xml file and delete name of removed file from it.

![](https://i.imgur.com/mVuCSxo.png)
